spring:
  application.name: bgserver
  r2dbc:
    url: "r2dbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: "jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}"
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  output.ansi.enabled: always
  ssl:
    bundle:
      pem:
        bgserver:
          keystore:
            certificate: "file:${CERT_PATH}"
            private-key: "file:${PRIVATE_KEY_PATH}"
  webflux:
    static-path-pattern: "/static/**"
logging.level:
  org.springframework.web: INFO
  org.springframework.r2dbc: INFO

custom:
  security:
    pepper: ${PEPPER_SECRET}
    jwt: ${JWT_SECRET}

server:
  ssl:
    bundle: bgserver
    enabled: true
  error:
    whitelabel:
      enabled: false