spring:
  application.name: bgserver
  r2dbc:
    url: "r2dbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}"
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    url: "jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DATABASE}"
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  output.ansi.enabled: always
  ssl:
    bundle:
      jks:
        bgserver:
          keystore:
            location: "file:${PKCS12_PATH}"
            password: ${PKCS12_PASSWORD}
            type: PKCS12
          reload-on-update: true
  webflux:
    static-path-pattern: "/static/**"
logging.level:
  org.springframework.web: INFO
  org.springframework.r2dbc: INFO

server:
  ssl:
    bundle: bgserver
    enabled: true